id: AEE1D7A9E
title: 'The Jewelled Rosary: An Aspiration Toward Longed-for Aims'
type: translation
pechas:
- ID3543BD4
- I6F082EB6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:37.944670
  last_modified_at: 2023-01-04 12:07:37.944677
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  ID3543BD4/1146: 1B60
  I6F082EB6/548C: 1B60
